export const servers = mysqlTable("servers", {
  id: int("id").autoincrement().primaryKey(),
  idMestre: varchar("idMestre", { length: 36 }).notNull().unique(),
  matricula: varchar("matricula", { length: 32 }).notNull().unique(),
  nomeOriginal: text("nomeOriginal").notNull(),
  nomeNormalizado: varchar("nomeNormalizado", { length: 255 }).notNull(),
  setor: varchar("setor", { length: 180 }),
  cargo: varchar("cargo", { length: 180 }),
  categoria: varchar("categoria", { length: 80 }),
  status: varchar("status", { length: 64 }).default("Ativo"),
  cpf: varchar("cpf", { length: 32 }).unique(),
  rg: varchar("rg", { length: 64 }),
  telefone: varchar("telefone", { length: 64 }),
  emailInstitucional: varchar("emailInstitucional", { length: 320 }),
  emailPessoal: varchar("emailPessoal", { length: 320 }),
  cargaHoraria: varchar("cargaHoraria", { length: 32 }),
  dataNascimento: date("dataNascimento"),
  dataContratacao: date("dataContratacao"),
  dataTerminoVigencia: date("dataTerminoVigencia"),
  participarComemoracao: mysqlEnum("participarComemoracao", ["Sim", "Não"]).default("Sim"),
  motivoNaoParticipar: varchar("motivoNaoParticipar", { length: 255 }),
  docenteClasse: varchar("docenteClasse", { length: 80 }),
  docenteNivel: varchar("docenteNivel", { length: 32 }),
  tecnicoNivel: int("tecnicoNivel"),
  grau: int("grau"),
  referencia: int("referencia"),
  estagiarioCalculaVigencia: mysqlEnum("estagiarioCalculaVigencia", ["Sim", "Não"]).default("Não"),
  contagemRenovacao: int("contagemRenovacao").default(0),
  terceirizadoSubstituto: mysqlEnum("terceirizadoSubstituto", ["Sim", "Não"]).default("Não"),
  idServidorSubstituido: int("idServidorSubstituido"),
  incentivoTipo: varchar("incentivoTipo", { length: 120 }),
  incentivoPortaria: varchar("incentivoPortaria", { length: 180 }),
  incentivoDataInicio: date("incentivoDataInicio"),
  incentivoDataValidade: date("incentivoDataValidade"),
  afastamentoMotivo: varchar("afastamentoMotivo", { length: 80 }),
  afastamentoDataInicio: date("afastamentoDataInicio"),
  afastamentoDataFim: date("afastamentoDataFim"),
  afastamentoDocumentoSei: varchar("afastamentoDocumentoSei", { length: 180 }),
  ultimaVarredura: timestamp("ultimaVarredura"),
  cargoComissionado: varchar("cargoComissionado", { length: 80 }),
  substitutoComissionado: varchar("substitutoComissionado", { length: 180 }),
  portariaSubstituicao: varchar("portariaSubstituicao", { length: 180 }),
  contrato: varchar("contrato", { length: 120 }),
  empresa: varchar("empresa", { length: 180 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
