import { CalendarDays, GraduationCap, Microscope, Timer, Building2 } from "lucide-react";

type Data = {
  servers: any[]; interns: any[]; productionIncentives: any[]; serviceRecords: any[]; contacts: any[];
  terceirizados: any[]; frequenciasTerceirizados: any[]; reviewQueue?: any[]; detectedPublications?: any[];
};
const fmt = (value: string | Date | null | undefined) => value ? new Date(value).toLocaleDateString("pt-BR") : "—";
const table = "w-full min-w-[760px] text-left text-sm";
const head = "bg-[#102641] text-[10px] uppercase tracking-[0.14em] text-white";

export function FunctionalModules({ active, data, onOpenMaster, onReview }: { active: string; data?: Data; onOpenMaster?: () => void; onReview?: (id: number, status: "resolved" | "ignored") => void }) {
  if (!data || !["estagiarios", "analises", "alertas", "aniversariantes", "fontes", "terceirizados"].includes(active)) return null;
  const configMap = {
    estagiarios: ["Estagiários", <GraduationCap className="h-5 w-5" />], analises: ["Produção Científica", <Microscope className="h-5 w-5" />],
    alertas: ["Tempo de Serviço", <Timer className="h-5 w-5" />], aniversariantes: ["Aniversariantes", <CalendarDays className="h-5 w-5" />],
    fontes: ["Fontes e auditoria", <CalendarDays className="h-5 w-5" />], terceirizados: ["Terceirizados", <Building2 className="h-5 w-5" />],
  };
  const config = configMap[active as keyof typeof configMap];
  return <section>
    <div className="mb-7 flex items-start gap-3"><div className="rounded-xl bg-[#102641] p-3 text-[#e3bc68]">{config[1]}</div><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#9a7940]">Dados persistidos · origem documentada</p><h1 className="mt-2 font-serif text-3xl font-semibold text-[#102641] md:text-4xl">{config[0]}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">Consulta ao banco funcional importado, com pendências e metadados preservados.</p></div><div className="ml-auto hidden rounded-xl border border-[#e4dfd4] bg-[#fffdf9] p-4 text-right sm:block"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#9a7940]">Somente consulta</p><p className="mt-1 text-xs text-slate-500">Alterações ficam na Base Mestre.</p>{onOpenMaster && <button onClick={onOpenMaster} className="mt-3 rounded-lg bg-[#102641] px-3 py-2 text-[11px] font-bold text-white">Abrir Servidores</button>}</div></div>
    <div className="overflow-hidden rounded-2xl border border-[#e4dfd4] bg-white shadow-sm"><div className="overflow-x-auto">
      {active === "estagiarios" && <table className={table}><thead className={head}><tr><th className="px-5 py-4">Matrícula</th><th className="px-5 py-4">Nome</th><th className="px-5 py-4">Curso / setor</th><th className="px-5 py-4">Processo</th><th className="px-5 py-4">Contratação</th></tr></thead><tbody className="divide-y divide-[#eeeae0]">{data.interns.map(row => <tr key={row.id}><td className="px-5 py-4 font-mono text-xs">{row.matricula ?? "PENDENTE"}</td><td className="px-5 py-4 font-semibold text-[#102641]">{row.nomeOriginal}</td><td className="px-5 py-4 text-slate-600">{row.cursando ?? "—"}<br /><span className="text-xs text-slate-400">{row.setorAtuacao ?? "Setor não informado"}</span></td><td className="px-5 py-4 text-xs text-slate-500">{row.numeroProcesso ?? "—"}</td><td className="px-5 py-4 text-slate-500">{fmt(row.dataContratacao)}</td></tr>)}</tbody></table>}
      {active === "analises" && <table className={table}><thead className={head}><tr><th className="px-5 py-4">Nome</th><th className="px-5 py-4">Matrícula</th><th className="px-5 py-4">Portaria</th><th className="px-5 py-4">Colegiado</th><th className="px-5 py-4">Vigência</th></tr></thead><tbody className="divide-y divide-[#eeeae0]">{[...data.productionIncentives].sort((a, b) => new Date(a.dataTermino ?? "9999-12-31").getTime() - new Date(b.dataTermino ?? "9999-12-31").getTime()).map(row => <tr key={row.id}><td className="px-5 py-4 font-semibold text-[#102641]">{row.nomeOriginal}</td><td className="px-5 py-4 font-mono text-xs">{row.matricula}</td><td className="px-5 py-4">{row.numeroPortaria}</td><td className="px-5 py-4">{row.colegiado}</td><td className="px-5 py-4 text-xs text-slate-500">{fmt(row.dataInicio)} – {fmt(row.dataTermino)} · {row.diasFaltantes}</td></tr>)}</tbody></table>}
      {active === "alertas" && <table className={table}><thead className={head}><tr><th className="px-5 py-4">Nome</th><th className="px-5 py-4">Cargo</th><th className="px-5 py-4">Setor</th><th className="px-5 py-4">Nascimento</th><th className="px-5 py-4">Ingresso</th><th className="px-5 py-4">Averbados</th></tr></thead><tbody className="divide-y divide-[#eeeae0]">{data.serviceRecords.map(row => <tr key={row.id}><td className="px-5 py-4 font-semibold text-[#102641]">{row.nomeOriginal}</td><td className="px-5 py-4">{row.cargo ?? "—"}</td><td className="px-5 py-4">{row.setor ?? "—"}</td><td className="px-5 py-4">{fmt(row.dataNascimento)}</td><td className="px-5 py-4">{fmt(row.dataContratacao)}</td><td className="px-5 py-4">{row.averbacaoDias ?? 0} dias</td></tr>)}</tbody></table>}
      {active === "aniversariantes" && <table className={table}><thead className={head}><tr><th className="px-5 py-4">Data</th><th className="px-5 py-4">Nome</th><th className="px-5 py-4">Vínculo</th><th className="px-5 py-4">Cargo / empresa</th><th className="px-5 py-4">Setor</th></tr></thead><tbody className="divide-y divide-[#eeeae0]">{[...data.servers.filter(row => row.dataNascimento && row.participarComemoracao !== "Não").map(row => ({ ...row, vinculo: row.categoria || "Servidor", detalhe: row.cargo, setor: row.setor })), ...data.interns.filter(row => row.dataNascimento).map(row => ({ ...row, vinculo: "Estagiário", detalhe: row.cursando })), ...data.terceirizados.filter(row => row.dataNascimento).map(row => ({ ...row, vinculo: "Terceirizado", detalhe: row.empresa }))].sort((a, b) => { const today = new Date(); const key = (value: string | Date) => { const date = new Date(value); return date.getMonth() < today.getMonth() || (date.getMonth() === today.getMonth() && date.getDate() < today.getDate()) ? 1 : 0; }; const da = new Date(a.dataNascimento); const db = new Date(b.dataNascimento); return key(a.dataNascimento) - key(b.dataNascimento) || da.getMonth() - db.getMonth() || da.getDate() - db.getDate(); }).map(row => <tr key={`${row.vinculo}-${row.id}`}><td className="px-5 py-4 font-semibold text-[#38536a]">{fmt(row.dataNascimento)}</td><td className="px-5 py-4 font-semibold text-[#102641]">{row.nomeOriginal}</td><td className="px-5 py-4">{row.vinculo}</td><td className="px-5 py-4">{row.detalhe ?? "—"}</td><td className="px-5 py-4">{row.setor ?? row.localLotacao ?? "—"}</td></tr>)}</tbody></table>}
      {active === "fontes" && <>
        <div className="grid gap-4 p-6 md:grid-cols-2">{data.contacts.map(row => <article key={row.id} className="rounded-xl border border-[#eeeae0] bg-[#fffdf9] p-5"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#9a7940]">{row.terceirizadoId ? "Contato de terceirizado" : "Contato importado"}</p><h2 className="mt-2 font-serif text-xl text-[#102641]">{row.nomeOriginal}</h2><p className="mt-3 text-sm text-slate-600">{row.setorOriginal ?? "Setor não informado"}</p><p className="mt-1 text-xs text-slate-500">{row.emailOriginal ?? "E-mail pendente"} · {row.telefoneOriginal ?? "Telefone pendente"}</p></article>)}</div>
        <div className="border-t border-[#eeeae0] p-6"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#9a7940]">Sincronização diária</p><h2 className="mt-1 font-serif text-2xl text-[#102641]">Fila de revisão institucional</h2></div><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-800">{(data.reviewQueue ?? []).filter(item => item.conflict?.status === "pending").length} pendentes</span></div><div className="mt-4 space-y-3">{(data.reviewQueue ?? []).filter(item => item.conflict?.status === "pending").map(item => { let details: any = {}; try { details = JSON.parse(item.conflict.details); } catch {} return <article key={item.conflict.id} className="rounded-xl border border-amber-200 bg-amber-50/50 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold text-[#102641]">{details.label ?? item.conflict.recordKey}</p><p className="mt-1 text-xs text-slate-600">{details.url ?? "Fonte institucional"} · HTTP {details.httpStatus ?? "—"}</p><p className="mt-2 text-xs leading-5 text-slate-600">{details.eventType ? `Publicação detectada: ${details.eventType}.` : "A fonte mudou ou ficou indisponível."} {details.extracted?.endDate ? `Retorno calculado: ${details.extracted.endDate}.` : ""} {details.extracted?.alert48h ? "Alerta: término em até 48 horas." : ""} Revise antes de qualquer incorporação na Base Mestre.</p></div><div className="flex gap-2"><button onClick={() => onReview?.(item.conflict.id, "resolved")} className="rounded-lg bg-[#102641] px-3 py-2 text-xs font-bold text-white">Confirmar e atualizar</button><button onClick={() => onReview?.(item.conflict.id, "ignored")} className="rounded-lg border border-[#d6cdbb] bg-white px-3 py-2 text-xs font-bold text-[#102641]">Descartar</button></div></div></article>; })}</div>
          <div className="mt-6 border-t border-[#eeeae0] pt-6"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#9a7940]">Histórico funcional</p><h2 className="mt-1 font-serif text-2xl text-[#102641]">Publicações PGDP detectadas</h2></div><span className="rounded-full bg-sky-100 px-3 py-1 text-xs font-bold text-sky-800">{data.detectedPublications?.length ?? 0} registros</span></div><div className="mt-4 space-y-2">{(data.detectedPublications ?? []).map(item => <article key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#eeeae0] bg-[#fffdf9] p-4"><div><p className="font-semibold text-[#102641]">{item.nomeOriginal ?? "Servidor não reconciliado"}</p><p className="mt-1 text-xs text-slate-600">{item.eventType} · {item.description}</p>{item.eventType === "carreira" && String(item.description ?? "").includes("confirmado") && <p className="mt-2 text-[11px] font-semibold text-emerald-700">Avanço de carreira confirmado · sugestão de atualização na Base Mestre — requer revisão</p>}<p className="mt-1 text-[11px] text-slate-500">{item.sourceLabel} · {fmt(item.publicationDate)} · {item.scanMode === "historical" ? "Carga histórica" : "Atualização diária"}</p></div>{item.documentUrl && <a className="rounded-lg border border-[#d6cdbb] px-3 py-2 text-xs font-bold text-[#102641]" href={item.documentUrl} target="_blank" rel="noreferrer">Abrir PDF</a>}</article>)}</div></div>
        </div>
      </>}
      {active === "terceirizados" && <div className="grid gap-4 p-5 md:grid-cols-2">{data.terceirizados.map(row => { const frequency = data.frequenciasTerceirizados.find(item => item.terceirizadoId === row.id); return <article key={row.id} className="rounded-2xl border border-[#e4dfd4] bg-[#fffdf9] p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#9a7940]">Terceirizado</p><h2 className="mt-2 font-serif text-xl text-[#102641]">{row.nomeOriginal}</h2></div><span className="rounded-full bg-amber-100 px-2.5 py-1 text-[10px] font-bold text-amber-800">{row.situacaoContrato ?? "Não informado"}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-[#102641] p-4 text-white"><p className="text-[10px] uppercase tracking-[0.14em] text-[#e3bc68]">Empresa</p><p className="mt-2 text-sm font-semibold">{row.empresa}</p></div><div className="rounded-xl bg-[#f5f1e9] p-4 text-[#102641]"><p className="text-[10px] uppercase tracking-[0.14em] text-[#9a7940]">Contrato</p><p className="mt-2 text-sm font-semibold">{row.contrato}</p></div></div><dl className="mt-5 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-xs text-slate-500">Função / turno</dt><dd className="font-semibold text-[#102641]">{row.cargoFuncao ?? "—"} · {frequency?.turno ?? "—"}</dd></div><div><dt className="text-xs text-slate-500">Lotação</dt><dd className="font-semibold text-[#102641]">{row.localLotacao ?? row.setor ?? "—"}</dd></div><div><dt className="text-xs text-slate-500">Última frequência</dt><dd className="font-semibold text-[#102641]">{frequency?.mesReferencia ?? "—"} · {frequency?.dias ?? "—"} dias</dd></div><div><dt className="text-xs text-slate-500">Substituto / ocorrência</dt><dd className="font-semibold text-[#102641]">{frequency?.substituto || frequency?.ocorrencias || "Nenhuma informada"}</dd></div></dl></article>; })}</div>}
    </div></div>
  </section>;
}
